### ISSUE TITLE
To be Done /notification to seller after product deletion  /send email to customer after creating an order

### ISSUE THREAD

**Issue by rihab-benali** [safwenHafsawy/PFE#21]

**Comment by safwenHafsawy** [comment]
notifiction price drops/return and refund customers/conversion rate/reviews statistics/ send mail to customer after deletion

**Comment by rihab-benali** [comment]
> notifiction price drops/return and refund customers/conversion rate/reviews statistics/ send mail to customer after deletion

/trending best category of the month
